apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  namespace: cpastore
  labels:
    app: db
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
        maxUnavailable: 0
  minReadySeconds: 20
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: db-deployment
        image: docker pull harbor.dev.afsmtddso.com/cpastore-harbor-project/db:06c0615-3475fc3
        ports:
        - containerPort: 5432
